[package]
name = "cms-mailer"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
cms-config = { workspace = true }
cms-error = { workspace = true }
lettre = { workspace = true }
minijinja = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }

[lints]
workspace = true
