[package]
name = "cms-authz"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
cms-entity = { path = "../cms-entity" }
cms-error = { path = "../cms-error" }
cms-db = { path = "../cms-db" }
serde = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }

[lints]
workspace = true
