/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ArRouteRouteImport } from './routes/ar/route'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DocumentationPlatformsRouteImport } from './routes/documentation-platforms'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SelfHostingRouteImport } from './routes/self-hosting'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as AcceptInviteInvitationIdRouteImport } from './routes/accept-invite.$invitationId'
import { Route as AlternativesGitbookRouteImport } from './routes/alternatives/gitbook'
import { Route as AlternativesMintlifyRouteImport } from './routes/alternatives/mintlify'
import { Route as AlternativesReadmeRouteImport } from './routes/alternatives/readme'
import { Route as AppdashboardRouteRouteImport } from './routes/app/(dashboard)/route'
import { Route as ArIndexRouteImport } from './routes/ar/index'
import { Route as ArDocumentationPlatformsRouteImport } from './routes/ar/documentation-platforms'
import { Route as ArGuidesRouteImport } from './routes/ar/guides'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CompareNibleafVsDocusaurusRouteImport } from './routes/compare/nibleaf-vs-docusaurus'
import { Route as CompareNibleafVsGitbookRouteImport } from './routes/compare/nibleaf-vs-gitbook'
import { Route as CompareNibleafVsMintlifyRouteImport } from './routes/compare/nibleaf-vs-mintlify'
import { Route as GitPreviewTokenRouteImport } from './routes/git-preview.$token'
import { Route as SitesProjectIdRouteRouteImport } from './routes/sites/$projectId/route'
import { Route as ToolsRtlDocumentationReadinessRouteImport } from './routes/tools/rtl-documentation-readiness'
import { Route as AppdashboardIndexRouteImport } from './routes/app/(dashboard)/index'
import { Route as AppdashboardAnalyticsRouteImport } from './routes/app/(dashboard)/analytics'
import { Route as AppdashboardMembersRouteImport } from './routes/app/(dashboard)/members'
import { Route as AppdashboardSettingsRouteImport } from './routes/app/(dashboard)/settings'
import { Route as AppdashboardSitesRouteImport } from './routes/app/(dashboard)/sites'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/app/projects/$projectId/route'
import { Route as SitesProjectIdIndexRouteImport } from './routes/sites/$projectId/index'
import { Route as SitesProjectIdSplatRouteImport } from './routes/sites/$projectId/$'
import { Route as SitesProjectIdChangelogRouteImport } from './routes/sites/$projectId/changelog'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects/$projectId/index'
import { Route as AppProjectsProjectIdAnalyticsRouteImport } from './routes/app/projects/$projectId/analytics'
import { Route as AppProjectsProjectIdEditorRouteImport } from './routes/app/projects/$projectId/editor'
import { Route as AppProjectsProjectIdPreviewRouteImport } from './routes/app/projects/$projectId/preview'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/app/projects/$projectId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRouteRoute = ArRouteRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentationPlatformsRoute = DocumentationPlatformsRouteImport.update({
  id: '/documentation-platforms',
  path: '/documentation-platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostingRoute = SelfHostingRouteImport.update({
  id: '/self-hosting',
  path: '/self-hosting',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const AcceptInviteInvitationIdRoute =
  AcceptInviteInvitationIdRouteImport.update({
    id: '/accept-invite/$invitationId',
    path: '/accept-invite/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlternativesGitbookRoute = AlternativesGitbookRouteImport.update({
  id: '/alternatives/gitbook',
  path: '/alternatives/gitbook',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativesMintlifyRoute = AlternativesMintlifyRouteImport.update({
  id: '/alternatives/mintlify',
  path: '/alternatives/mintlify',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativesReadmeRoute = AlternativesReadmeRouteImport.update({
  id: '/alternatives/readme',
  path: '/alternatives/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const AppdashboardRouteRoute = AppdashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => AppRouteRoute,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArRouteRoute,
} as any)
const ArDocumentationPlatformsRoute =
  ArDocumentationPlatformsRouteImport.update({
    id: '/documentation-platforms',
    path: '/documentation-platforms',
    getParentRoute: () => ArRouteRoute,
  } as any)
const ArGuidesRoute = ArGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => ArRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareNibleafVsDocusaurusRoute =
  CompareNibleafVsDocusaurusRouteImport.update({
    id: '/compare/nibleaf-vs-docusaurus',
    path: '/compare/nibleaf-vs-docusaurus',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareNibleafVsGitbookRoute = CompareNibleafVsGitbookRouteImport.update({
  id: '/compare/nibleaf-vs-gitbook',
  path: '/compare/nibleaf-vs-gitbook',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareNibleafVsMintlifyRoute =
  CompareNibleafVsMintlifyRouteImport.update({
    id: '/compare/nibleaf-vs-mintlify',
    path: '/compare/nibleaf-vs-mintlify',
    getParentRoute: () => rootRouteImport,
  } as any)
const GitPreviewTokenRoute = GitPreviewTokenRouteImport.update({
  id: '/git-preview/$token',
  path: '/git-preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesProjectIdRouteRoute = SitesProjectIdRouteRouteImport.update({
  id: '/sites/$projectId',
  path: '/sites/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRtlDocumentationReadinessRoute =
  ToolsRtlDocumentationReadinessRouteImport.update({
    id: '/tools/rtl-documentation-readiness',
    path: '/tools/rtl-documentation-readiness',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppdashboardIndexRoute = AppdashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardAnalyticsRoute = AppdashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardMembersRoute = AppdashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardSettingsRoute = AppdashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardSitesRoute = AppdashboardSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const SitesProjectIdIndexRoute = SitesProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitesProjectIdRouteRoute,
} as any)
const SitesProjectIdSplatRoute = SitesProjectIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SitesProjectIdRouteRoute,
} as any)
const SitesProjectIdChangelogRoute = SitesProjectIdChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => SitesProjectIdRouteRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdAnalyticsRoute =
  AppProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdEditorRoute =
  AppProjectsProjectIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdPreviewRoute =
  AppProjectsProjectIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppdashboardRouteRouteWithChildren
  '/ar': typeof ArRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/documentation-platforms': typeof DocumentationPlatformsRoute
  '/guides': typeof GuidesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/self-hosting': typeof SelfHostingRoute
  '/terms': typeof TermsRoute
  '/sites/$projectId': typeof SitesProjectIdRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/alternatives/gitbook': typeof AlternativesGitbookRoute
  '/alternatives/mintlify': typeof AlternativesMintlifyRoute
  '/alternatives/readme': typeof AlternativesReadmeRoute
  '/ar/documentation-platforms': typeof ArDocumentationPlatformsRoute
  '/ar/guides': typeof ArGuidesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/nibleaf-vs-docusaurus': typeof CompareNibleafVsDocusaurusRoute
  '/compare/nibleaf-vs-gitbook': typeof CompareNibleafVsGitbookRoute
  '/compare/nibleaf-vs-mintlify': typeof CompareNibleafVsMintlifyRoute
  '/git-preview/$token': typeof GitPreviewTokenRoute
  '/tools/rtl-documentation-readiness': typeof ToolsRtlDocumentationReadinessRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/analytics': typeof AppdashboardAnalyticsRoute
  '/app/members': typeof AppdashboardMembersRoute
  '/app/settings': typeof AppdashboardSettingsRoute
  '/app/sites': typeof AppdashboardSitesRoute
  '/sites/$projectId/$': typeof SitesProjectIdSplatRoute
  '/sites/$projectId/changelog': typeof SitesProjectIdChangelogRoute
  '/app/': typeof AppdashboardIndexRoute
  '/sites/$projectId/': typeof SitesProjectIdIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/editor': typeof AppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/preview': typeof AppProjectsProjectIdPreviewRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppdashboardIndexRoute
  '/about': typeof AboutRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/documentation-platforms': typeof DocumentationPlatformsRoute
  '/guides': typeof GuidesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/self-hosting': typeof SelfHostingRoute
  '/terms': typeof TermsRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/alternatives/gitbook': typeof AlternativesGitbookRoute
  '/alternatives/mintlify': typeof AlternativesMintlifyRoute
  '/alternatives/readme': typeof AlternativesReadmeRoute
  '/ar/documentation-platforms': typeof ArDocumentationPlatformsRoute
  '/ar/guides': typeof ArGuidesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/nibleaf-vs-docusaurus': typeof CompareNibleafVsDocusaurusRoute
  '/compare/nibleaf-vs-gitbook': typeof CompareNibleafVsGitbookRoute
  '/compare/nibleaf-vs-mintlify': typeof CompareNibleafVsMintlifyRoute
  '/git-preview/$token': typeof GitPreviewTokenRoute
  '/tools/rtl-documentation-readiness': typeof ToolsRtlDocumentationReadinessRoute
  '/ar': typeof ArIndexRoute
  '/blog': typeof BlogIndexRoute
  '/app/analytics': typeof AppdashboardAnalyticsRoute
  '/app/members': typeof AppdashboardMembersRoute
  '/app/settings': typeof AppdashboardSettingsRoute
  '/app/sites': typeof AppdashboardSitesRoute
  '/sites/$projectId/$': typeof SitesProjectIdSplatRoute
  '/sites/$projectId/changelog': typeof SitesProjectIdChangelogRoute
  '/sites/$projectId': typeof SitesProjectIdIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/editor': typeof AppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/preview': typeof AppProjectsProjectIdPreviewRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/ar': typeof ArRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/developers': typeof DevelopersRoute
  '/documentation-platforms': typeof DocumentationPlatformsRoute
  '/guides': typeof GuidesRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/self-hosting': typeof SelfHostingRoute
  '/terms': typeof TermsRoute
  '/app/(dashboard)': typeof AppdashboardRouteRouteWithChildren
  '/sites/$projectId': typeof SitesProjectIdRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/alternatives/gitbook': typeof AlternativesGitbookRoute
  '/alternatives/mintlify': typeof AlternativesMintlifyRoute
  '/alternatives/readme': typeof AlternativesReadmeRoute
  '/ar/documentation-platforms': typeof ArDocumentationPlatformsRoute
  '/ar/guides': typeof ArGuidesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/nibleaf-vs-docusaurus': typeof CompareNibleafVsDocusaurusRoute
  '/compare/nibleaf-vs-gitbook': typeof CompareNibleafVsGitbookRoute
  '/compare/nibleaf-vs-mintlify': typeof CompareNibleafVsMintlifyRoute
  '/git-preview/$token': typeof GitPreviewTokenRoute
  '/tools/rtl-documentation-readiness': typeof ToolsRtlDocumentationReadinessRoute
  '/ar/': typeof ArIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/(dashboard)/analytics': typeof AppdashboardAnalyticsRoute
  '/app/(dashboard)/members': typeof AppdashboardMembersRoute
  '/app/(dashboard)/settings': typeof AppdashboardSettingsRoute
  '/app/(dashboard)/sites': typeof AppdashboardSitesRoute
  '/sites/$projectId/$': typeof SitesProjectIdSplatRoute
  '/sites/$projectId/changelog': typeof SitesProjectIdChangelogRoute
  '/app/(dashboard)/': typeof AppdashboardIndexRoute
  '/sites/$projectId/': typeof SitesProjectIdIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/editor': typeof AppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/preview': typeof AppProjectsProjectIdPreviewRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/ar'
    | '/about'
    | '/cloud'
    | '/contact'
    | '/developers'
    | '/documentation-platforms'
    | '/guides'
    | '/pricing'
    | '/privacy'
    | '/self-hosting'
    | '/terms'
    | '/sites/$projectId'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invite/$invitationId'
    | '/alternatives/gitbook'
    | '/alternatives/mintlify'
    | '/alternatives/readme'
    | '/ar/documentation-platforms'
    | '/ar/guides'
    | '/blog/$slug'
    | '/compare/nibleaf-vs-docusaurus'
    | '/compare/nibleaf-vs-gitbook'
    | '/compare/nibleaf-vs-mintlify'
    | '/git-preview/$token'
    | '/tools/rtl-documentation-readiness'
    | '/ar/'
    | '/blog/'
    | '/app/projects/$projectId'
    | '/app/analytics'
    | '/app/members'
    | '/app/settings'
    | '/app/sites'
    | '/sites/$projectId/$'
    | '/sites/$projectId/changelog'
    | '/app/'
    | '/sites/$projectId/'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/preview'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/about'
    | '/cloud'
    | '/contact'
    | '/developers'
    | '/documentation-platforms'
    | '/guides'
    | '/pricing'
    | '/privacy'
    | '/self-hosting'
    | '/terms'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invite/$invitationId'
    | '/alternatives/gitbook'
    | '/alternatives/mintlify'
    | '/alternatives/readme'
    | '/ar/documentation-platforms'
    | '/ar/guides'
    | '/blog/$slug'
    | '/compare/nibleaf-vs-docusaurus'
    | '/compare/nibleaf-vs-gitbook'
    | '/compare/nibleaf-vs-mintlify'
    | '/git-preview/$token'
    | '/tools/rtl-documentation-readiness'
    | '/ar'
    | '/blog'
    | '/app/analytics'
    | '/app/members'
    | '/app/settings'
    | '/app/sites'
    | '/sites/$projectId/$'
    | '/sites/$projectId/changelog'
    | '/sites/$projectId'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/preview'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/ar'
    | '/about'
    | '/cloud'
    | '/contact'
    | '/developers'
    | '/documentation-platforms'
    | '/guides'
    | '/pricing'
    | '/privacy'
    | '/self-hosting'
    | '/terms'
    | '/app/(dashboard)'
    | '/sites/$projectId'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/accept-invite/$invitationId'
    | '/alternatives/gitbook'
    | '/alternatives/mintlify'
    | '/alternatives/readme'
    | '/ar/documentation-platforms'
    | '/ar/guides'
    | '/blog/$slug'
    | '/compare/nibleaf-vs-docusaurus'
    | '/compare/nibleaf-vs-gitbook'
    | '/compare/nibleaf-vs-mintlify'
    | '/git-preview/$token'
    | '/tools/rtl-documentation-readiness'
    | '/ar/'
    | '/blog/'
    | '/app/projects/$projectId'
    | '/app/(dashboard)/analytics'
    | '/app/(dashboard)/members'
    | '/app/(dashboard)/settings'
    | '/app/(dashboard)/sites'
    | '/sites/$projectId/$'
    | '/sites/$projectId/changelog'
    | '/app/(dashboard)/'
    | '/sites/$projectId/'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/preview'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ArRouteRoute: typeof ArRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CloudRoute: typeof CloudRoute
  ContactRoute: typeof ContactRoute
  DevelopersRoute: typeof DevelopersRoute
  DocumentationPlatformsRoute: typeof DocumentationPlatformsRoute
  GuidesRoute: typeof GuidesRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SelfHostingRoute: typeof SelfHostingRoute
  TermsRoute: typeof TermsRoute
  SitesProjectIdRouteRoute: typeof SitesProjectIdRouteRouteWithChildren
  AcceptInviteInvitationIdRoute: typeof AcceptInviteInvitationIdRoute
  AlternativesGitbookRoute: typeof AlternativesGitbookRoute
  AlternativesMintlifyRoute: typeof AlternativesMintlifyRoute
  AlternativesReadmeRoute: typeof AlternativesReadmeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompareNibleafVsDocusaurusRoute: typeof CompareNibleafVsDocusaurusRoute
  CompareNibleafVsGitbookRoute: typeof CompareNibleafVsGitbookRoute
  CompareNibleafVsMintlifyRoute: typeof CompareNibleafVsMintlifyRoute
  GitPreviewTokenRoute: typeof GitPreviewTokenRoute
  ToolsRtlDocumentationReadinessRoute: typeof ToolsRtlDocumentationReadinessRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentation-platforms': {
      id: '/documentation-platforms'
      path: '/documentation-platforms'
      fullPath: '/documentation-platforms'
      preLoaderRoute: typeof DocumentationPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-hosting': {
      id: '/self-hosting'
      path: '/self-hosting'
      fullPath: '/self-hosting'
      preLoaderRoute: typeof SelfHostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/accept-invite/$invitationId': {
      id: '/accept-invite/$invitationId'
      path: '/accept-invite/$invitationId'
      fullPath: '/accept-invite/$invitationId'
      preLoaderRoute: typeof AcceptInviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatives/gitbook': {
      id: '/alternatives/gitbook'
      path: '/alternatives/gitbook'
      fullPath: '/alternatives/gitbook'
      preLoaderRoute: typeof AlternativesGitbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatives/mintlify': {
      id: '/alternatives/mintlify'
      path: '/alternatives/mintlify'
      fullPath: '/alternatives/mintlify'
      preLoaderRoute: typeof AlternativesMintlifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternatives/readme': {
      id: '/alternatives/readme'
      path: '/alternatives/readme'
      fullPath: '/alternatives/readme'
      preLoaderRoute: typeof AlternativesReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(dashboard)': {
      id: '/app/(dashboard)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppdashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/ar/': {
      id: '/ar/'
      path: '/'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof ArRouteRoute
    }
    '/ar/documentation-platforms': {
      id: '/ar/documentation-platforms'
      path: '/documentation-platforms'
      fullPath: '/ar/documentation-platforms'
      preLoaderRoute: typeof ArDocumentationPlatformsRouteImport
      parentRoute: typeof ArRouteRoute
    }
    '/ar/guides': {
      id: '/ar/guides'
      path: '/guides'
      fullPath: '/ar/guides'
      preLoaderRoute: typeof ArGuidesRouteImport
      parentRoute: typeof ArRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/nibleaf-vs-docusaurus': {
      id: '/compare/nibleaf-vs-docusaurus'
      path: '/compare/nibleaf-vs-docusaurus'
      fullPath: '/compare/nibleaf-vs-docusaurus'
      preLoaderRoute: typeof CompareNibleafVsDocusaurusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/nibleaf-vs-gitbook': {
      id: '/compare/nibleaf-vs-gitbook'
      path: '/compare/nibleaf-vs-gitbook'
      fullPath: '/compare/nibleaf-vs-gitbook'
      preLoaderRoute: typeof CompareNibleafVsGitbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/nibleaf-vs-mintlify': {
      id: '/compare/nibleaf-vs-mintlify'
      path: '/compare/nibleaf-vs-mintlify'
      fullPath: '/compare/nibleaf-vs-mintlify'
      preLoaderRoute: typeof CompareNibleafVsMintlifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/git-preview/$token': {
      id: '/git-preview/$token'
      path: '/git-preview/$token'
      fullPath: '/git-preview/$token'
      preLoaderRoute: typeof GitPreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$projectId': {
      id: '/sites/$projectId'
      path: '/sites/$projectId'
      fullPath: '/sites/$projectId'
      preLoaderRoute: typeof SitesProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rtl-documentation-readiness': {
      id: '/tools/rtl-documentation-readiness'
      path: '/tools/rtl-documentation-readiness'
      fullPath: '/tools/rtl-documentation-readiness'
      preLoaderRoute: typeof ToolsRtlDocumentationReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(dashboard)/': {
      id: '/app/(dashboard)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppdashboardIndexRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/analytics': {
      id: '/app/(dashboard)/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppdashboardAnalyticsRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/members': {
      id: '/app/(dashboard)/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppdashboardMembersRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/settings': {
      id: '/app/(dashboard)/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppdashboardSettingsRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/sites': {
      id: '/app/(dashboard)/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppdashboardSitesRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/sites/$projectId/': {
      id: '/sites/$projectId/'
      path: '/'
      fullPath: '/sites/$projectId/'
      preLoaderRoute: typeof SitesProjectIdIndexRouteImport
      parentRoute: typeof SitesProjectIdRouteRoute
    }
    '/sites/$projectId/$': {
      id: '/sites/$projectId/$'
      path: '/$'
      fullPath: '/sites/$projectId/$'
      preLoaderRoute: typeof SitesProjectIdSplatRouteImport
      parentRoute: typeof SitesProjectIdRouteRoute
    }
    '/sites/$projectId/changelog': {
      id: '/sites/$projectId/changelog'
      path: '/changelog'
      fullPath: '/sites/$projectId/changelog'
      preLoaderRoute: typeof SitesProjectIdChangelogRouteImport
      parentRoute: typeof SitesProjectIdRouteRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/analytics': {
      id: '/app/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/app/projects/$projectId/analytics'
      preLoaderRoute: typeof AppProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/editor': {
      id: '/app/projects/$projectId/editor'
      path: '/editor'
      fullPath: '/app/projects/$projectId/editor'
      preLoaderRoute: typeof AppProjectsProjectIdEditorRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/preview': {
      id: '/app/projects/$projectId/preview'
      path: '/preview'
      fullPath: '/app/projects/$projectId/preview'
      preLoaderRoute: typeof AppProjectsProjectIdPreviewRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/settings': {
      id: '/app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/app/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppdashboardRouteRouteChildren {
  AppdashboardAnalyticsRoute: typeof AppdashboardAnalyticsRoute
  AppdashboardMembersRoute: typeof AppdashboardMembersRoute
  AppdashboardSettingsRoute: typeof AppdashboardSettingsRoute
  AppdashboardSitesRoute: typeof AppdashboardSitesRoute
  AppdashboardIndexRoute: typeof AppdashboardIndexRoute
}

const AppdashboardRouteRouteChildren: AppdashboardRouteRouteChildren = {
  AppdashboardAnalyticsRoute: AppdashboardAnalyticsRoute,
  AppdashboardMembersRoute: AppdashboardMembersRoute,
  AppdashboardSettingsRoute: AppdashboardSettingsRoute,
  AppdashboardSitesRoute: AppdashboardSitesRoute,
  AppdashboardIndexRoute: AppdashboardIndexRoute,
}

const AppdashboardRouteRouteWithChildren =
  AppdashboardRouteRoute._addFileChildren(AppdashboardRouteRouteChildren)

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdAnalyticsRoute: typeof AppProjectsProjectIdAnalyticsRoute
  AppProjectsProjectIdEditorRoute: typeof AppProjectsProjectIdEditorRoute
  AppProjectsProjectIdPreviewRoute: typeof AppProjectsProjectIdPreviewRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdAnalyticsRoute: AppProjectsProjectIdAnalyticsRoute,
    AppProjectsProjectIdEditorRoute: AppProjectsProjectIdEditorRoute,
    AppProjectsProjectIdPreviewRoute: AppProjectsProjectIdPreviewRoute,
    AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
    AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppdashboardRouteRoute: typeof AppdashboardRouteRouteWithChildren
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppdashboardRouteRoute: AppdashboardRouteRouteWithChildren,
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ArRouteRouteChildren {
  ArDocumentationPlatformsRoute: typeof ArDocumentationPlatformsRoute
  ArGuidesRoute: typeof ArGuidesRoute
  ArIndexRoute: typeof ArIndexRoute
}

const ArRouteRouteChildren: ArRouteRouteChildren = {
  ArDocumentationPlatformsRoute: ArDocumentationPlatformsRoute,
  ArGuidesRoute: ArGuidesRoute,
  ArIndexRoute: ArIndexRoute,
}

const ArRouteRouteWithChildren =
  ArRouteRoute._addFileChildren(ArRouteRouteChildren)

interface SitesProjectIdRouteRouteChildren {
  SitesProjectIdSplatRoute: typeof SitesProjectIdSplatRoute
  SitesProjectIdChangelogRoute: typeof SitesProjectIdChangelogRoute
  SitesProjectIdIndexRoute: typeof SitesProjectIdIndexRoute
}

const SitesProjectIdRouteRouteChildren: SitesProjectIdRouteRouteChildren = {
  SitesProjectIdSplatRoute: SitesProjectIdSplatRoute,
  SitesProjectIdChangelogRoute: SitesProjectIdChangelogRoute,
  SitesProjectIdIndexRoute: SitesProjectIdIndexRoute,
}

const SitesProjectIdRouteRouteWithChildren =
  SitesProjectIdRouteRoute._addFileChildren(SitesProjectIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  ArRouteRoute: ArRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CloudRoute: CloudRoute,
  ContactRoute: ContactRoute,
  DevelopersRoute: DevelopersRoute,
  DocumentationPlatformsRoute: DocumentationPlatformsRoute,
  GuidesRoute: GuidesRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SelfHostingRoute: SelfHostingRoute,
  TermsRoute: TermsRoute,
  SitesProjectIdRouteRoute: SitesProjectIdRouteRouteWithChildren,
  AcceptInviteInvitationIdRoute: AcceptInviteInvitationIdRoute,
  AlternativesGitbookRoute: AlternativesGitbookRoute,
  AlternativesMintlifyRoute: AlternativesMintlifyRoute,
  AlternativesReadmeRoute: AlternativesReadmeRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompareNibleafVsDocusaurusRoute: CompareNibleafVsDocusaurusRoute,
  CompareNibleafVsGitbookRoute: CompareNibleafVsGitbookRoute,
  CompareNibleafVsMintlifyRoute: CompareNibleafVsMintlifyRoute,
  GitPreviewTokenRoute: GitPreviewTokenRoute,
  ToolsRtlDocumentationReadinessRoute: ToolsRtlDocumentationReadinessRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
