import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: [
    'src/brand/index.ts',
    'src/theme/theme-provider.tsx',
    'src/lib/utils.ts',
    'src/hooks/use-mobile.ts',
    'src/hooks/use-otp-resend-countdown.ts',
    'src/components/ui/accordion.tsx',
    'src/components/ui/alert.tsx',
    'src/components/ui/avatar.tsx',
    'src/components/ui/badge.tsx',
    'src/components/ui/breadcrumb.tsx',
    'src/components/ui/button.tsx',
    'src/components/ui/card.tsx',
    'src/components/ui/chart.tsx',
    'src/components/ui/collapsible.tsx',
    'src/components/ui/command.tsx',
    'src/components/ui/confirm.tsx',
    'src/components/ui/dialog.tsx',
    'src/components/ui/direction.tsx',
    'src/components/ui/dropdown-menu.tsx',
    'src/components/ui/form-field.tsx',
    'src/components/ui/input-group.tsx',
    'src/components/ui/input-otp.tsx',
    'src/components/ui/input.tsx',
    'src/components/ui/label.tsx',
    'src/components/ui/popover.tsx',
    'src/components/ui/progress.tsx',
    'src/components/ui/scroll-area.tsx',
    'src/components/ui/segmented-control.tsx',
    'src/components/ui/select.tsx',
    'src/components/ui/separator.tsx',
    'src/components/ui/sheet.tsx',
    'src/components/ui/sidebar.tsx',
    'src/components/ui/skeleton.tsx',
    'src/components/ui/slider.tsx',
    'src/components/ui/sonner.tsx',
    'src/components/ui/switch.tsx',
    'src/components/ui/table.tsx',
    'src/components/ui/tabs.tsx',
    'src/components/ui/textarea.tsx',
    'src/components/ui/tooltip.tsx',
  ],
  format: ['esm'],
  platform: 'browser',
  dts: false,
  clean: true,
  sourcemap: true,
});
