import { THEME_REPOSITORY_TEMPLATE_META, type ThemeRepositoryTemplateOptions } from './types';

const contentDir = (root: string) => (root ? `${root}/` : './');

export const readmeTemplate = (options: ThemeRepositoryTemplateOptions): string => {
  const { projectName, contentRoot, languages, templateId } = options;
  const meta = THEME_REPOSITORY_TEMPLATE_META[templateId];
  const content = contentDir(contentRoot);
  const secondary = languages.find((language) => !language.isDefault);
  const defaultLanguage = languages.find((language) => language.isDefault) ?? languages[0];
  const secondaryExample = secondary ? `${content}${secondary.code}/getting-started.mdx` : `${content}fr/getting-started.mdx`;
  return `# ${projectName}

Documentation site for **${projectName}**, generated by [cms](https://cms.com) as a normal, runnable
[TanStack Start](https://tanstack.com/start) + Vite + Tailwind CSS v4 application. Pages are MDX files under
\`${content}\`; navigation and theme tokens come from \`docs.json\` (Mintlify-compatible). Nothing here depends on the
cms monorepo, no secrets are required, and the build makes no network requests.

## Run it

\`\`\`sh
corepack pnpm install
corepack pnpm dev      # http://localhost:3000
corepack pnpm build    # static site in .output/public (+ optional Node server in .output/server)
corepack pnpm preview  # serve the production build locally
corepack pnpm test     # vitest
corepack pnpm check    # tests + build + typecheck before pushing
\`\`\`

The build prerenders every page reachable from \`/\` (\`tanstackStart({ prerender: { enabled: true, crawlLinks: true } })\`),
so \`.output/public\` deploys to Vercel, Netlify, Cloudflare Pages, GitHub Pages, or any static host. \`/\` renders the
first page of the default language (${defaultLanguage?.label ?? 'default'}); every other page lives at its content path.

## Add a page

1. Create \`${content}guides/rate-limits.mdx\`. Folders are navigation groups, \`index.mdx\` is a folder's landing page.
2. Start the file with frontmatter — exactly what cms writes back:

   \`\`\`mdx
   ---
   title: "Rate limits"
   description: "How quotas are enforced."
   icon: "gauge"
   ---

   ## Overview
   \`\`\`

3. Run \`pnpm dev\`. A page that is not (yet) listed in \`docs.json\` is appended to its group automatically (fumadocs
   "rest" semantics), so the site keeps working while cms catches up. Set \`hidden: true\` to keep a page out of
   navigation and search.

## Add a language or version

- Default language (${defaultLanguage?.code ?? 'en'}) pages sit at the content root. Other languages live in
  \`${content}<code>/\` (for example \`${secondaryExample}\`). The URL prefix mirrors the folder and \`<html lang dir>\`
  follows the language declared in \`docs.json\` — right-to-left languages render RTL end to end.
- Non-default versions live in \`${content}versions/<version>/\` with the same language layout inside.
- Language and version metadata (labels, direction, defaults) is managed in cms and regenerated into \`docs.json\`.

## Change the look

- \`src/components/layout/${meta.componentName}.tsx\` is the ${meta.displayName} shell (${meta.shell}). The other two
  shells ship alongside it; \`src/components/layout/index.tsx\` picks one from \`docs.json\` → \`x-cms.theme.layout.shell\`.
- \`src/styles.css\` maps the theme tokens in \`docs.json\` to Tailwind utilities (\`bg-canvas\`, \`text-accent\`, …) for
  light and dark mode. Colors regenerate from cms; utilities, prose styles, and component styles are yours.
- \`src/components/mdx/\` renders the cms MDX components (Callout, Card, Tabs, Steps, FileTree, …). Markdown is
  rendered at runtime through \`react-markdown\` + \`rehype-sanitize\`, so untrusted content never becomes code.
- \`messages/{en,ar}.json\` hold the bilingual chrome strings (Paraglide).

## Who owns what

| Path | Owner | cms sync behaviour |
| --- | --- | --- |
| \`docs.json\`, \`.cms/**\` | PLATFORM | Regenerated and verified on every sync. Do not hand-edit — edits become conflicts. |
| \`${content}**/*.mdx\` | SHARED | Three-way merged from the recorded common base; competing edits require an explicit resolution. |
| \`src/**\`, \`messages/**\`, \`public/**\`, \`package.json\`, config files, this README | CUSTOMER | Seeded once, never overwritten. Git is authoritative, including deletion. |

## How this compares

| Concern | fumadocs | Mintlify | This repository |
| --- | --- | --- | --- |
| Content | \`content/docs/**/*.mdx\` | \`**/*.mdx\` | \`${content}**/*.mdx\` (folders = groups) |
| Navigation | \`meta.json\` per folder | \`docs.json\` | \`docs.json\` (generated) + rest semantics |
| i18n | \`page.ar.mdx\` / \`ar/\` folder | folder per language | \`${content}<lang>/\` |
| Runtime | Next.js app | hosted | TanStack Start app (static build) |
| Theming | CSS variables | \`docs.json\` colors | \`docs.json\` \`x-cms.theme\` → Tailwind tokens |
`;
};
