import { json, type ThemeRepositoryTemplateOptions } from './types';

export const tsconfigTemplate = (): string =>
  json({
    compilerOptions: {
      target: 'ES2023',
      lib: ['ES2023', 'DOM', 'DOM.Iterable'],
      module: 'ESNext',
      moduleResolution: 'Bundler',
      jsx: 'react-jsx',
      strict: true,
      // Paraglide emits typed JS message modules under src/paraglide.
      allowJs: true,
      skipLibCheck: true,
      isolatedModules: true,
      verbatimModuleSyntax: true,
      allowImportingTsExtensions: true,
      resolveJsonModule: true,
      esModuleInterop: true,
      noEmit: true,
      types: ['vite/client', 'node'],
    },
    include: ['src', 'vite.config.ts', 'vitest.config.ts', 'docs.json'],
  });

export const viteConfigTemplate = (): string => `import { paraglideVitePlugin } from '@inlang/paraglide-js';
import tailwindcss from '@tailwindcss/vite';
import { tanstackStart } from '@tanstack/react-start/plugin/vite';
import react from '@vitejs/plugin-react';
import { nitro } from 'nitro/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [
    // Bilingual chrome strings live in messages/*.json and compile to src/paraglide.
    paraglideVitePlugin({ project: './project.inlang', outdir: './src/paraglide' }),
    tailwindcss(),
    nitro(),
    // Every page reachable from "/" is prerendered, so "pnpm build" yields a static
    // site under .output/public that any static host can serve. The Node server in
    // .output/server is optional.
    tanstackStart({ prerender: { enabled: true, crawlLinks: true, autoSubfolderIndex: true } }),
    react({ compiler: true }),
  ],
});
`;

export const vitestConfigTemplate = (): string => `import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: { environment: 'node', include: ['src/**/*.test.{ts,tsx}'] },
});
`;

export const gitignoreTemplate = (): string =>
  ['node_modules', 'dist', '.output', '.nitro', '.tanstack', 'src/paraglide', '.env', '.env.local', ''].join('\n');

export const inlangSettingsTemplate = (): string =>
  json({
    $schema: 'https://inlang.com/schema/project-settings',
    baseLocale: 'en',
    locales: ['en', 'ar'],
    modules: ['https://cdn.jsdelivr.net/npm/@inlang/plugin-message-format@4/dist/index.js'],
    'plugin.inlang.messageFormat': { pathPattern: './messages/{locale}.json' },
  });

export const faviconTemplate = ({ theme }: ThemeRepositoryTemplateOptions): string =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="${theme.colors.light.accent}"/><path d="M17 43V21h7l16 13V21h7v22h-7L24 30v13z" fill="${theme.colors.light.accentForeground}"/></svg>\n`;

/** TanStack Router regenerates this file on every dev/build run; shipping a
 * matching version lets `tsc --noEmit` pass before the first build. */
export const routeTreeTemplate = (): string => `/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$'
  id: '__root__' | '/' | '/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
`;
