export const DOCUMENTATION_COMPONENT_SCHEMA_VERSION = 1 as const;

export type DocumentationComponentCategory = 'structure' | 'emphasis' | 'media' | 'api' | 'navigation' | 'inline';
export type DocumentationComponentSyntax = 'mdx' | 'markdown' | 'fence';

export interface DocumentationComponentCapability {
  id: string;
  syntax: DocumentationComponentSyntax;
  tag?: string;
  category: DocumentationComponentCategory;
  kind: 'block' | 'inline';
  attributes: readonly string[];
  allowedChildren?: readonly string[];
  visualEditor: boolean;
  interactive: boolean;
}

/**
 * Public, code-only authoring contract shared by the editor, renderer, exports,
 * and capability adapters. Entries describe authored syntax only: consumers
 * must never interpret File/Folder names as repository paths or fetch component
 * attributes over the network.
 */
export const DOCUMENTATION_COMPONENT_CATALOG = [
  { id: 'callout', syntax: 'mdx', tag: 'Callout', category: 'emphasis', kind: 'block', attributes: ['type'], visualEditor: true, interactive: false },
  { id: 'note', syntax: 'mdx', tag: 'Note', category: 'emphasis', kind: 'block', attributes: [], visualEditor: true, interactive: false },
  { id: 'tip', syntax: 'mdx', tag: 'Tip', category: 'emphasis', kind: 'block', attributes: [], visualEditor: true, interactive: false },
  { id: 'check', syntax: 'mdx', tag: 'Check', category: 'emphasis', kind: 'block', attributes: [], visualEditor: true, interactive: false },
  { id: 'warning', syntax: 'mdx', tag: 'Warning', category: 'emphasis', kind: 'block', attributes: [], visualEditor: true, interactive: false },
  { id: 'danger', syntax: 'mdx', tag: 'Danger', category: 'emphasis', kind: 'block', attributes: [], visualEditor: true, interactive: false },
  {
    id: 'card-group',
    syntax: 'mdx',
    tag: 'CardGroup',
    category: 'navigation',
    kind: 'block',
    attributes: ['cols'],
    allowedChildren: ['Card'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'card',
    syntax: 'mdx',
    tag: 'Card',
    category: 'navigation',
    kind: 'block',
    attributes: ['title', 'icon', 'href'],
    visualEditor: true,
    interactive: true,
  },
  {
    id: 'steps',
    syntax: 'mdx',
    tag: 'Steps',
    category: 'structure',
    kind: 'block',
    attributes: [],
    allowedChildren: ['Step'],
    visualEditor: true,
    interactive: false,
  },
  { id: 'step', syntax: 'mdx', tag: 'Step', category: 'structure', kind: 'block', attributes: ['title'], visualEditor: true, interactive: false },
  {
    id: 'tabs',
    syntax: 'mdx',
    tag: 'Tabs',
    category: 'structure',
    kind: 'block',
    attributes: [],
    allowedChildren: ['Tab'],
    visualEditor: true,
    interactive: true,
  },
  { id: 'tab', syntax: 'mdx', tag: 'Tab', category: 'structure', kind: 'block', attributes: ['title'], visualEditor: true, interactive: false },
  {
    id: 'accordion-group',
    syntax: 'mdx',
    tag: 'AccordionGroup',
    category: 'structure',
    kind: 'block',
    attributes: [],
    allowedChildren: ['Accordion'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'accordion',
    syntax: 'mdx',
    tag: 'Accordion',
    category: 'structure',
    kind: 'block',
    attributes: ['title', 'defaultOpen'],
    visualEditor: true,
    interactive: true,
  },
  { id: 'code-group', syntax: 'mdx', tag: 'CodeGroup', category: 'api', kind: 'block', attributes: [], visualEditor: true, interactive: true },
  { id: 'frame', syntax: 'mdx', tag: 'Frame', category: 'media', kind: 'block', attributes: ['caption'], visualEditor: true, interactive: false },
  { id: 'image', syntax: 'markdown', category: 'media', kind: 'block', attributes: ['src', 'alt', 'title'], visualEditor: true, interactive: false },
  { id: 'table', syntax: 'markdown', category: 'structure', kind: 'block', attributes: [], visualEditor: true, interactive: false },
  { id: 'code-block', syntax: 'fence', category: 'api', kind: 'block', attributes: ['language', 'title'], visualEditor: true, interactive: true },
  { id: 'mermaid', syntax: 'fence', category: 'media', kind: 'block', attributes: [], visualEditor: true, interactive: true },
  {
    id: 'param-field',
    syntax: 'mdx',
    tag: 'ParamField',
    category: 'api',
    kind: 'block',
    attributes: ['path', 'query', 'header', 'body', 'name', 'type', 'required', 'default', 'deprecated'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'response-field',
    syntax: 'mdx',
    tag: 'ResponseField',
    category: 'api',
    kind: 'block',
    attributes: ['name', 'type', 'required', 'default', 'deprecated'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'expandable',
    syntax: 'mdx',
    tag: 'Expandable',
    category: 'api',
    kind: 'block',
    attributes: ['title', 'defaultOpen'],
    visualEditor: true,
    interactive: true,
  },
  {
    id: 'columns',
    syntax: 'mdx',
    tag: 'Columns',
    category: 'structure',
    kind: 'block',
    attributes: [],
    allowedChildren: ['Column'],
    visualEditor: true,
    interactive: false,
  },
  { id: 'column', syntax: 'mdx', tag: 'Column', category: 'structure', kind: 'block', attributes: [], visualEditor: true, interactive: false },
  { id: 'banner', syntax: 'mdx', tag: 'Banner', category: 'emphasis', kind: 'block', attributes: ['type'], visualEditor: true, interactive: false },
  { id: 'badge', syntax: 'mdx', tag: 'Badge', category: 'inline', kind: 'inline', attributes: ['color'], visualEditor: true, interactive: false },
  {
    id: 'button',
    syntax: 'mdx',
    tag: 'Button',
    category: 'inline',
    kind: 'inline',
    attributes: ['href', 'variant'],
    visualEditor: true,
    interactive: true,
  },
  { id: 'tooltip', syntax: 'mdx', tag: 'Tooltip', category: 'inline', kind: 'inline', attributes: ['tip'], visualEditor: true, interactive: true },
  {
    id: 'icon',
    syntax: 'mdx',
    tag: 'Icon',
    category: 'inline',
    kind: 'inline',
    attributes: ['icon', 'name', 'color', 'size'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'update',
    syntax: 'mdx',
    tag: 'Update',
    category: 'emphasis',
    kind: 'block',
    attributes: ['label', 'description'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'file-tree',
    syntax: 'mdx',
    tag: 'FileTree',
    category: 'structure',
    kind: 'block',
    attributes: [],
    allowedChildren: ['Folder', 'File'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'folder',
    syntax: 'mdx',
    tag: 'Folder',
    category: 'structure',
    kind: 'block',
    attributes: ['name', 'defaultOpen'],
    allowedChildren: ['Folder', 'File'],
    visualEditor: true,
    interactive: true,
  },
  {
    id: 'file',
    syntax: 'mdx',
    tag: 'File',
    category: 'structure',
    kind: 'block',
    attributes: ['name', 'icon'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'api-example',
    syntax: 'mdx',
    tag: 'ApiExample',
    category: 'api',
    kind: 'block',
    attributes: ['title'],
    allowedChildren: ['RequestExample', 'ResponseExample'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'request-example',
    syntax: 'mdx',
    tag: 'RequestExample',
    category: 'api',
    kind: 'block',
    attributes: ['title'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'response-example',
    syntax: 'mdx',
    tag: 'ResponseExample',
    category: 'api',
    kind: 'block',
    attributes: ['title', 'status'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'related-content',
    syntax: 'mdx',
    tag: 'RelatedContent',
    category: 'navigation',
    kind: 'block',
    attributes: ['title'],
    allowedChildren: ['RelatedCard'],
    visualEditor: true,
    interactive: false,
  },
  {
    id: 'related-card',
    syntax: 'mdx',
    tag: 'RelatedCard',
    category: 'navigation',
    kind: 'block',
    attributes: ['title', 'description', 'href', 'icon'],
    visualEditor: true,
    interactive: true,
  },
] as const satisfies readonly DocumentationComponentCapability[];

export const documentationComponentTags = (): readonly string[] =>
  DOCUMENTATION_COMPONENT_CATALOG.flatMap((component: DocumentationComponentCapability) => (component.tag ? [component.tag] : []));
