/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as AcceptInviteInvitationIdRouteImport } from './routes/accept-invite.$invitationId'
import { Route as AppdashboardRouteRouteImport } from './routes/app/(dashboard)/route'
import { Route as GitPreviewTokenRouteImport } from './routes/git-preview.$token'
import { Route as SitesProjectIdRouteRouteImport } from './routes/sites/$projectId/route'
import { Route as AppdashboardIndexRouteImport } from './routes/app/(dashboard)/index'
import { Route as AppdashboardAnalyticsRouteImport } from './routes/app/(dashboard)/analytics'
import { Route as AppdashboardMembersRouteImport } from './routes/app/(dashboard)/members'
import { Route as AppdashboardSettingsRouteImport } from './routes/app/(dashboard)/settings'
import { Route as AppdashboardSitesRouteImport } from './routes/app/(dashboard)/sites'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/app/projects/$projectId/route'
import { Route as SitesProjectIdIndexRouteImport } from './routes/sites/$projectId/index'
import { Route as SitesProjectIdSplatRouteImport } from './routes/sites/$projectId/$'
import { Route as SitesProjectIdChangelogRouteImport } from './routes/sites/$projectId/changelog'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/app/projects/$projectId/index'
import { Route as AppProjectsProjectIdAnalyticsRouteImport } from './routes/app/projects/$projectId/analytics'
import { Route as AppProjectsProjectIdEditorRouteImport } from './routes/app/projects/$projectId/editor'
import { Route as AppProjectsProjectIdPreviewRouteImport } from './routes/app/projects/$projectId/preview'
import { Route as AppProjectsProjectIdSettingsRouteImport } from './routes/app/projects/$projectId/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => authRouteRoute,
} as any)
const AcceptInviteInvitationIdRoute =
  AcceptInviteInvitationIdRouteImport.update({
    id: '/accept-invite/$invitationId',
    path: '/accept-invite/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppdashboardRouteRoute = AppdashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => AppRouteRoute,
} as any)
const GitPreviewTokenRoute = GitPreviewTokenRouteImport.update({
  id: '/git-preview/$token',
  path: '/git-preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesProjectIdRouteRoute = SitesProjectIdRouteRouteImport.update({
  id: '/sites/$projectId',
  path: '/sites/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppdashboardIndexRoute = AppdashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardAnalyticsRoute = AppdashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardMembersRoute = AppdashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardSettingsRoute = AppdashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppdashboardSitesRoute = AppdashboardSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppdashboardRouteRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const SitesProjectIdIndexRoute = SitesProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SitesProjectIdRouteRoute,
} as any)
const SitesProjectIdSplatRoute = SitesProjectIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SitesProjectIdRouteRoute,
} as any)
const SitesProjectIdChangelogRoute = SitesProjectIdChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => SitesProjectIdRouteRoute,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdAnalyticsRoute =
  AppProjectsProjectIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdEditorRoute =
  AppProjectsProjectIdEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdPreviewRoute =
  AppProjectsProjectIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdSettingsRoute =
  AppProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppdashboardRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/onboarding': typeof OnboardingRoute
  '/sites/$projectId': typeof SitesProjectIdRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/git-preview/$token': typeof GitPreviewTokenRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/analytics': typeof AppdashboardAnalyticsRoute
  '/app/members': typeof AppdashboardMembersRoute
  '/app/settings': typeof AppdashboardSettingsRoute
  '/app/sites': typeof AppdashboardSitesRoute
  '/sites/$projectId/$': typeof SitesProjectIdSplatRoute
  '/sites/$projectId/changelog': typeof SitesProjectIdChangelogRoute
  '/app/': typeof AppdashboardIndexRoute
  '/sites/$projectId/': typeof SitesProjectIdIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/editor': typeof AppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/preview': typeof AppProjectsProjectIdPreviewRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppdashboardIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/git-preview/$token': typeof GitPreviewTokenRoute
  '/app/analytics': typeof AppdashboardAnalyticsRoute
  '/app/members': typeof AppdashboardMembersRoute
  '/app/settings': typeof AppdashboardSettingsRoute
  '/app/sites': typeof AppdashboardSitesRoute
  '/sites/$projectId/$': typeof SitesProjectIdSplatRoute
  '/sites/$projectId/changelog': typeof SitesProjectIdChangelogRoute
  '/sites/$projectId': typeof SitesProjectIdIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/editor': typeof AppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/preview': typeof AppProjectsProjectIdPreviewRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/onboarding': typeof OnboardingRoute
  '/app/(dashboard)': typeof AppdashboardRouteRouteWithChildren
  '/sites/$projectId': typeof SitesProjectIdRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/git-preview/$token': typeof GitPreviewTokenRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/app/(dashboard)/analytics': typeof AppdashboardAnalyticsRoute
  '/app/(dashboard)/members': typeof AppdashboardMembersRoute
  '/app/(dashboard)/settings': typeof AppdashboardSettingsRoute
  '/app/(dashboard)/sites': typeof AppdashboardSitesRoute
  '/sites/$projectId/$': typeof SitesProjectIdSplatRoute
  '/sites/$projectId/changelog': typeof SitesProjectIdChangelogRoute
  '/app/(dashboard)/': typeof AppdashboardIndexRoute
  '/sites/$projectId/': typeof SitesProjectIdIndexRoute
  '/app/projects/$projectId/analytics': typeof AppProjectsProjectIdAnalyticsRoute
  '/app/projects/$projectId/editor': typeof AppProjectsProjectIdEditorRoute
  '/app/projects/$projectId/preview': typeof AppProjectsProjectIdPreviewRoute
  '/app/projects/$projectId/settings': typeof AppProjectsProjectIdSettingsRoute
  '/app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/accept-invitation'
    | '/onboarding'
    | '/sites/$projectId'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invite/$invitationId'
    | '/git-preview/$token'
    | '/app/projects/$projectId'
    | '/app/analytics'
    | '/app/members'
    | '/app/settings'
    | '/app/sites'
    | '/sites/$projectId/$'
    | '/sites/$projectId/changelog'
    | '/app/'
    | '/sites/$projectId/'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/preview'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/accept-invitation'
    | '/onboarding'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/accept-invite/$invitationId'
    | '/git-preview/$token'
    | '/app/analytics'
    | '/app/members'
    | '/app/settings'
    | '/app/sites'
    | '/sites/$projectId/$'
    | '/sites/$projectId/changelog'
    | '/sites/$projectId'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/preview'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/app'
    | '/accept-invitation'
    | '/onboarding'
    | '/app/(dashboard)'
    | '/sites/$projectId'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/accept-invite/$invitationId'
    | '/git-preview/$token'
    | '/app/projects/$projectId'
    | '/app/(dashboard)/analytics'
    | '/app/(dashboard)/members'
    | '/app/(dashboard)/settings'
    | '/app/(dashboard)/sites'
    | '/sites/$projectId/$'
    | '/sites/$projectId/changelog'
    | '/app/(dashboard)/'
    | '/sites/$projectId/'
    | '/app/projects/$projectId/analytics'
    | '/app/projects/$projectId/editor'
    | '/app/projects/$projectId/preview'
    | '/app/projects/$projectId/settings'
    | '/app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  OnboardingRoute: typeof OnboardingRoute
  SitesProjectIdRouteRoute: typeof SitesProjectIdRouteRouteWithChildren
  AcceptInviteInvitationIdRoute: typeof AcceptInviteInvitationIdRoute
  GitPreviewTokenRoute: typeof GitPreviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/accept-invite/$invitationId': {
      id: '/accept-invite/$invitationId'
      path: '/accept-invite/$invitationId'
      fullPath: '/accept-invite/$invitationId'
      preLoaderRoute: typeof AcceptInviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(dashboard)': {
      id: '/app/(dashboard)'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppdashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/git-preview/$token': {
      id: '/git-preview/$token'
      path: '/git-preview/$token'
      fullPath: '/git-preview/$token'
      preLoaderRoute: typeof GitPreviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$projectId': {
      id: '/sites/$projectId'
      path: '/sites/$projectId'
      fullPath: '/sites/$projectId'
      preLoaderRoute: typeof SitesProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/(dashboard)/': {
      id: '/app/(dashboard)/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppdashboardIndexRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/analytics': {
      id: '/app/(dashboard)/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppdashboardAnalyticsRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/members': {
      id: '/app/(dashboard)/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppdashboardMembersRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/settings': {
      id: '/app/(dashboard)/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppdashboardSettingsRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/(dashboard)/sites': {
      id: '/app/(dashboard)/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppdashboardSitesRouteImport
      parentRoute: typeof AppdashboardRouteRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/sites/$projectId/': {
      id: '/sites/$projectId/'
      path: '/'
      fullPath: '/sites/$projectId/'
      preLoaderRoute: typeof SitesProjectIdIndexRouteImport
      parentRoute: typeof SitesProjectIdRouteRoute
    }
    '/sites/$projectId/$': {
      id: '/sites/$projectId/$'
      path: '/$'
      fullPath: '/sites/$projectId/$'
      preLoaderRoute: typeof SitesProjectIdSplatRouteImport
      parentRoute: typeof SitesProjectIdRouteRoute
    }
    '/sites/$projectId/changelog': {
      id: '/sites/$projectId/changelog'
      path: '/changelog'
      fullPath: '/sites/$projectId/changelog'
      preLoaderRoute: typeof SitesProjectIdChangelogRouteImport
      parentRoute: typeof SitesProjectIdRouteRoute
    }
    '/app/projects/$projectId/': {
      id: '/app/projects/$projectId/'
      path: '/'
      fullPath: '/app/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/analytics': {
      id: '/app/projects/$projectId/analytics'
      path: '/analytics'
      fullPath: '/app/projects/$projectId/analytics'
      preLoaderRoute: typeof AppProjectsProjectIdAnalyticsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/editor': {
      id: '/app/projects/$projectId/editor'
      path: '/editor'
      fullPath: '/app/projects/$projectId/editor'
      preLoaderRoute: typeof AppProjectsProjectIdEditorRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/preview': {
      id: '/app/projects/$projectId/preview'
      path: '/preview'
      fullPath: '/app/projects/$projectId/preview'
      preLoaderRoute: typeof AppProjectsProjectIdPreviewRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/app/projects/$projectId/settings': {
      id: '/app/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/app/projects/$projectId/settings'
      preLoaderRoute: typeof AppProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AppdashboardRouteRouteChildren {
  AppdashboardAnalyticsRoute: typeof AppdashboardAnalyticsRoute
  AppdashboardMembersRoute: typeof AppdashboardMembersRoute
  AppdashboardSettingsRoute: typeof AppdashboardSettingsRoute
  AppdashboardSitesRoute: typeof AppdashboardSitesRoute
  AppdashboardIndexRoute: typeof AppdashboardIndexRoute
}

const AppdashboardRouteRouteChildren: AppdashboardRouteRouteChildren = {
  AppdashboardAnalyticsRoute: AppdashboardAnalyticsRoute,
  AppdashboardMembersRoute: AppdashboardMembersRoute,
  AppdashboardSettingsRoute: AppdashboardSettingsRoute,
  AppdashboardSitesRoute: AppdashboardSitesRoute,
  AppdashboardIndexRoute: AppdashboardIndexRoute,
}

const AppdashboardRouteRouteWithChildren =
  AppdashboardRouteRoute._addFileChildren(AppdashboardRouteRouteChildren)

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdAnalyticsRoute: typeof AppProjectsProjectIdAnalyticsRoute
  AppProjectsProjectIdEditorRoute: typeof AppProjectsProjectIdEditorRoute
  AppProjectsProjectIdPreviewRoute: typeof AppProjectsProjectIdPreviewRoute
  AppProjectsProjectIdSettingsRoute: typeof AppProjectsProjectIdSettingsRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdAnalyticsRoute: AppProjectsProjectIdAnalyticsRoute,
    AppProjectsProjectIdEditorRoute: AppProjectsProjectIdEditorRoute,
    AppProjectsProjectIdPreviewRoute: AppProjectsProjectIdPreviewRoute,
    AppProjectsProjectIdSettingsRoute: AppProjectsProjectIdSettingsRoute,
    AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppdashboardRouteRoute: typeof AppdashboardRouteRouteWithChildren
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppdashboardRouteRoute: AppdashboardRouteRouteWithChildren,
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SitesProjectIdRouteRouteChildren {
  SitesProjectIdSplatRoute: typeof SitesProjectIdSplatRoute
  SitesProjectIdChangelogRoute: typeof SitesProjectIdChangelogRoute
  SitesProjectIdIndexRoute: typeof SitesProjectIdIndexRoute
}

const SitesProjectIdRouteRouteChildren: SitesProjectIdRouteRouteChildren = {
  SitesProjectIdSplatRoute: SitesProjectIdSplatRoute,
  SitesProjectIdChangelogRoute: SitesProjectIdChangelogRoute,
  SitesProjectIdIndexRoute: SitesProjectIdIndexRoute,
}

const SitesProjectIdRouteRouteWithChildren =
  SitesProjectIdRouteRoute._addFileChildren(SitesProjectIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  OnboardingRoute: OnboardingRoute,
  SitesProjectIdRouteRoute: SitesProjectIdRouteRouteWithChildren,
  AcceptInviteInvitationIdRoute: AcceptInviteInvitationIdRoute,
  GitPreviewTokenRoute: GitPreviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
